spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:movienow}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:movienow}
    password: ${POSTGRES_PASSWORD:movienow123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:user}
    password: ${SPRING_RABBITMQ_PASSWORD:user}

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:laclaveporDefectoBienLargaYSegura12345678901234567890}
  
  
sendgrid:
  api-key: ${SENDGRID_API_KEY}

movienow:
  api:
    url: https://api.themoviedb.org/3
    key: ${MOVIENOW_API_KEY:63eb8176e16fea085c5f5bd32708b0ec}
    token: ${MOVIENOW_API_TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2M2ViODE3NmUxNmZlYTA4NWM1ZjViZDMyNzA4YjBlYyIsIm5iZiI6MTc2MDM5NDY0Ni42MjEsInN1YiI6IjY4ZWQ3ZDk2NzY3Y2E3ZmM3MTI4MjczZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.UWkzk5J2_A7OuaoADcwYGc_E9azDsYOZ9QW3Cz-dneA}



# -----------------------------
# OBSERVABILIDAD (Actuator + Micrometer/Prometheus)
# -----------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: movienow-backend

  tracing:
    enabled: false


app:
  rabbitmq:
    exchange: user.exchange
    routing-key: user.created
    queue: user.created.queue

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:5174

