spring:

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:h2:mem:movienowdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

jwt:
    secret: laclavesecreta345346g45y245H$th34H&$H%&H$%yh345y234ty4YHG$%Hsdfjmwguiwh4#%345rgh4g#%YGH#$%H$%H45hw4h